### ISSUE TITLE
Optional ServerName and DatabaseName for Native

### ISSUE THREAD

**Issue by mitrov** [jhoek/UncommonSense.Nav.Automation#11]
In case of SQL Client: ServerName and DatabaseName should be mandatory
In case of Native Client: only one of the two parameters is needed (local vs. server installation)

This should be doable with parameter sets.

Another option might be dynamic parameters:
https://msdn.microsoft.com/en-us/library/dd878299(v=vs.85).aspx
http://www.powershellmagazine.com/2014/05/29/dynamic-parameters-in-powershell/

**Comment by jhoek** [comment]
That application of dynamics parameters I didn't know about yet. I have used them for displaying parameter values that could not be known before run-time. I'll take a look at your links soon!

**Comment by jhoek** [comment]
@mitrov Please take Test-DynamicParams for a spin. Is that more or less what you meant?

**Comment by mitrov** [comment]
I haven't tested it yet but it looks very good!

**Comment by jhoek** [comment]
Thx. I think I will build the logic into Get-NAVDevelopmentClient and get rid of the Test-* functions.

**Comment by jhoek** [comment]
Tried to get my dynamic parameters to work in combination with parameter sets, because -List and -DatabaseServerType {Sql or Native} should be mutually exclusive. Couldn't get it to work. After converting  -DatabaseServerType to two switches (-Sql and -Native), everything now works *without* dynamic parameters, which I believe makes this solution easier to maintain.

**Comment by jhoek** [comment]
Implemented in Get-NAVDevelopmentClient.
