### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by jhoek** [jhoek/UncommonSense.Nav.Automation#14]

**Comment by mitrov** [comment]
NAV language & ZupPath in configs.txt:

When working with NAV txt object files it is recommended to use the ENU language.
The language of the NAV client (Dev. Environment) is stored inside the Zup file.

The ZupPath in configs.txt should point to a Zup-File which is used exclusively for the powershell scripts. Since we cannot change the language to ENU with powershell, it has to be done by the user manually by selecting ENU inside the NAV client.
This of course is only needed in mulitlanguage environments where ENU is not the default language.
