### ISSUE TITLE
Get-NAVDevelopmentClient settings parameters like filters

### ISSUE THREAD

**Issue by jhoek** [jhoek/UncommonSense.Nav.Automation#17]
What if...
- Get-NAVDevelopmentClient's settings parameters (-Sql, -Native, -DatabaseServerName, -DatabaseName) were merely filters;
- Parameter -List would return the entire list; not specifying -List would return the first matching client;
- None of the settings parameters would be mandatory, and all of them would allow wildcards; 
- The -Config parameter could simply retrieve setting parameter values from the configs.txt, and call itself with those values as filters

**Comment by mitrov** [comment]
-> Parameter -List would return the entire list; not specifying -List would return the first matching client;

Sounds dangerous to me. I wouldn't want to mix up dev.-clients when it comes to exporting, comparing and importing NAV objects. Since I work with many different codebases at the same time I would try to make it as tight as possible and make sure I work with the correct dev.-clients.

But I have to test the latest scripts first before worrying about it too much. Just let me know @jhoek  when you think I should clone the repo and fool around with the scripts.

**Comment by jhoek** [comment]
You're right in the sense that e.g. -DatabaseServerName *A* could potentially match many different servers, but wildcard-less parameter values such as -DatabaseServerName MyParticularServerName would match exactly one.

Also I'm thinking about differentiating between -DatabaseServerName and -LiteralDatabaseServerName, much like -Path and -LiteralPath in e.g. Add-Content. These literal parameters would also be what is used when you specify the -Config parameter.
